enable-magisk-update = true

patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "RVX-anddea"

patches-version = "v2.228.0-dev.11"
integrations-version = "v0.155.0-dev.6"

[YouTube]
included-patches = "'Custom branding icon for YouTube' 'MaterialYou'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Music]
excluded-patches = "'Enable Cairo splash animation'"
included-patches = "'Custom branding icon for YouTube Music' 'Custom header for YouTube Music'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
